export const routes = {
  home: '/',
  login: '/login',
  register: '/register',
  search: '/search',
  calendar: '/calendar',
  docsRoot: '/docs',
  docsIntroduction: '/docs/introduction',
  docsPattern: '/docs/:slug',
  docs: (slug: string) => `/docs/${encodeURIComponent(slug)}`,
  me: '/me',
  library: '/library',
  collections: '/collections',
  reviews: '/reviews',
  devApi: '/dev/api',
  subject: (subjectId: string) => `/subjects/${encodeURIComponent(subjectId)}`,
  subjectPattern: '/subjects/:subjectId',
} as const;
