export const routes = {
  home: '/',
  login: '/login',
  register: '/register',
  resetPassword: '/password/reset',
  search: '/search',
  calendar: '/calendar',
  docsRoot: '/docs',
  docsIntroduction: '/docs/introduction',
  docsPattern: '/docs/:slug',
  docs: (slug: string) => `/docs/${encodeURIComponent(slug)}`,
  communityPosts: '/community/posts',
  communityPostPattern: '/community/posts/:postId',
  communityPost: (postId: number | string) => `/community/posts/${encodeURIComponent(String(postId))}`,
  userProfilePattern: '/users/:userId',
  userProfile: (userId: number | string) => `/users/${encodeURIComponent(String(userId))}`,
  userFollowersPattern: '/users/:userId/followers',
  userFollowers: (userId: number | string) => `/users/${encodeURIComponent(String(userId))}/followers`,
  userFollowingPattern: '/users/:userId/following',
  userFollowing: (userId: number | string) => `/users/${encodeURIComponent(String(userId))}/following`,
  userReviewsPattern: '/users/:userId/reviews',
  userReviews: (userId: number | string) => `/users/${encodeURIComponent(String(userId))}/reviews`,
  userSubjectsPattern: '/users/:userId/entities',
  userSubjects: (userId: number | string) => `/users/${encodeURIComponent(String(userId))}/entities`,
  userCollectionsPattern: '/users/:userId/collections',
  userCollections: (userId: number | string) => `/users/${encodeURIComponent(String(userId))}/collections`,
  userCollectionPattern: '/users/:userId/collections/:collectionId',
  userCollection: (userId: number | string, collectionId: number | string) =>
    `/users/${encodeURIComponent(String(userId))}/collections/${encodeURIComponent(String(collectionId))}`,
  notifications: '/notifications',
  bookmarks: '/bookmarks',
  admin: '/admin',
  me: '/me',
  settings: '/settings',
  library: '/library',
  collections: '/collections',
  reviews: '/reviews',
  reviewNew: '/reviews/new',
  reviewPattern: '/reviews/:reviewId',
  reviewEditPattern: '/reviews/:reviewId/edit',
  reviewNewForSubject: (subjectId: string) => `/reviews/new?subjectId=${encodeURIComponent(subjectId)}`,
  review: (reviewId: number | string) => `/reviews/${encodeURIComponent(String(reviewId))}`,
  reviewEdit: (reviewId: number | string) => `/reviews/${encodeURIComponent(String(reviewId))}/edit`,
  entity: (subjectId: string) => `/entities/${encodeURIComponent(subjectId)}`,
  entityPattern: '/entities/:subjectId',
  entityGraph: (subjectId: string) => `/entities/${encodeURIComponent(subjectId)}/graph`,
  entityGraphPattern: '/entities/:subjectId/graph',
} as const;
